name:ilk workflowumuz


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  
  workflow dispatch:
    
jobs:
    deneme:
        runs-on: ubuntu-latest
        steps:
            -name: Checkout
            users: actions/checkout@v4
            -name: Hello World
             run:
                echo "Hello World"
                printenv